### ISSUE TITLE
warning: variable does not need to be mutable

### ISSUE THREAD

**Issue by asomers** [mindsbackyard/galvanic-test#1]
When I try to use galvanic_test, all of my test cases print a warning like this when compiling:
```
warning: variable does not need to be mutable
  --> tests/mutable_self.rs:3:1
   |
3  | / test_suite! {
4  | |     name dummy;
5  | |
6  | |     fixture!( foo() -> isize {
...  |
13 | |     }
14 | | }
   | |_^
   |
   = note: #[warn(unused_mut)] on by default
   = note: this error originates in a macro outside of the current crate
```
I believe the cause is the `&mut self` argument to `setup`.  On a test without members, the `mut` shouldn't be necessary.   However, I can't remove it, because then I get an `error: no rules expected the token self` error.  Here is an example test suite that demonstrates the problem:
```rust
#[macro_use] extern crate galvanic_test;
  
test_suite! {
    name dummy;

    fixture!( foo() -> isize {
        setup(&mut self) {
            42
        }
    });

    test t(foo) {
        assert_eq!(42, foo.val);
    }
}
```

**Comment by austinbes** [comment]
Definitely second this -- it's interesting to note that the warnings occur when building this crate, too.

**Comment by austinbes** [comment]
I'm currently band-aiding it as follows:

```Rust
test_suite! {
    name dummy;

    fixture foo -> isize {
        setup(&mut self) {
            42
        }
    }

    #[allow(unused_mut)]
    test t(foo) {
        assert_eq!(42, foo.val);
    }
}
```

However, this isn't a great solution since it has to be applied to every test, and since it applies to the *whole* test. I'd definitely like to get warnings for unused mutable values *other* than those in fixtures.

**Comment by mindsbackyard** [comment]
That's definitely an issue. I've got to check the root cause of it. The `mut` on self isn't always necessary from a user perspective, though if I remember correctly there are some situations where it's needed for internal reasons. I'll have a look. Applying `#[allow(unused_must)]` for fixing it isn't a viable option.

**Comment by mindsbackyard** [comment]
The warnings have been removed by adding a noop function which takes a mutable borrow of a FixtureBinding. That's crude but it suppresses the warning and the code generation would not be able to distinguish between mut/non-mut use cases.
The fixed library is now available as v0.1.2

**Comment by austinbes** [comment]
Love the fast response on this

**Comment by austinbes** [comment]
On my machine (running the latest nightly), I still get a warning.

MWE:

```Rust
#[macro_use] extern crate galvanic_test;

test_suite! {
    test dummy() {
        assert!(true);
    }
}
```

Warning:

```
warning: function is never used: `noop`
 --> src/lib.rs:3:1
  |
3 | / test_suite! {
4 | |     test dummy() {
5 | |         assert!(true);
6 | |     }
7 | | }
  | |_^
  |
  = note: #[warn(dead_code)] on by default
  = note: this error originates in a macro outside of the current crate

    Finished dev [unoptimized + debuginfo] target(s) in 0.60 secs
     Running target/debug/deps/galvanic_mwe-67ed880421a4d1cf
```

This is with `Cargo.toml` pointed explicitly at version 0.1.2
