### ISSUE TITLE
Can't run a basic test

### ISSUE THREAD

**Issue by Dowwie** [mindsbackyard/galvanic-test#10]
This is such a great addition to the Rust ecosystem.  I've used pytest extensively and am so glad to find others with an interest in continuing its testing patterns in Rust.

However, I can't manage to get a very basic test to run.

Is this project working?

**Comment by mindsbackyard** [comment]
Sorry for the late answer. Yes, basically the project works (not perfectly though). But without more information I can't really help you. Did you have a look at the tests? Those should demonstrate working examples.

**Comment by mindsbackyard** [comment]
Closing due to missing further input
