### ISSUE TITLE
Typo in the readme led to error when running testsuite

### ISSUE THREAD

**Issue by grapemix** [mindsbackyard/galvanic-test#12]
When I tried to run the testsuite by following the instruction in the readme: I got this:
"this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)"

It turns out that the readme used the word "use_macros" which is wrong. For example, "#[use_macros] extern crate galvanic_test;".

If I replace with "macro_use", everything is fine.

Finally, this crate is awesome. Thx for the contribution to the community. I do hope in the future we get something like db transnational rollback in each testcase, but that will need hell lots of work....

**Comment by mindsbackyard** [comment]
Thanks, for spotting the mistake. I've fixed it in 0.1.4 and also some other issues with the current nightly.

Also thanks for the nice words, I appreciate it. Regarding the other feature you mentioned, could you elaborate it in another issue? Not sure if I can manage it but I'd give it a try if its useful/possible/I've-got-time. PRs are welcome too.
