### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by LunicLynx** [mindsbackyard/galvanic-test#16]
If I follow the current [Documentation](https://github.com/mindsbackyard/galvanic-test#documentation) i get the following error:

```shell
error[E0463]: can't find crate for `galvanic_test`
 --> src\lib.rs:3:1
  |
3 | extern crate galvanic_test;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

Which makes sense because we only added it as a `[dev-dependencies]`. So i only got it working, by annotating it with `#[cfg(test)]` like so:

```rust
#[cfg(test)]
#[macro_use]
extern crate galvanic_test;

#[cfg(test)]
mod tests {
    use galvanic_test::*;

    // ... tests ...
}
```

But I'm new to testing in rust, Is there something I'm missing?

**Comment by mindsbackyard** [comment]
You are right, if you the crate as a dev-dependency then a `#[cfg(test)]` is required for except for integration tests (those in the `tests/` folder). I've updated the Readme in `v0.2.0` (edition 2018 support) to make the users aware. Thanks for the issue!
