### ISSUE TITLE
Support for edition 2018

### ISSUE THREAD

**Issue by vorner** [mindsbackyard/galvanic-test#17]
I can't seem to be able to make it work with the new way (importing macros by use). No matter what I try, it complains `__test_suite_int`, even if I try to import it.

```rust
use galvanic_test::{test_suite, __test_suite_int};

fn main() {

}

test_suite! {

}
```

(complains only on `cargo test`, not `cargo build`, and I can still use the old `#[macro_use] extern crate;`)

**Comment by mindsbackyard** [comment]
Support for edition 2018 has now been added to `v0.2.0`. The Readme has also been updated accordingly. A simple `use galvanic_test::test_suite;` should suffice.
